leftnav:
- identifier: 27f59991-8869-44d1-bd27-9c3d77c800ac
  name: google
  pageRef: /links/google
  weight: 10
- identifier: a1adb31c-9da8-4c70-b7c8-c35f5da1b981
  name: External Blog
  pageRef: /external-resources/an-external-blog
  weight: 20
