leftnav:
- identifier: 8ae51073-ba25-4f26-9d50-86ec0e189c7d
  name: page
  pageRef: /pages/page
  weight: 10
- identifier: 27f59991-8869-44d1-bd27-9c3d77c800ac
  name: google
  pageRef: /links/google
  weight: 20
- identifier: fdd9274a-9eac-4fe5-b83d-2141ade9d26f
  name: image
  pageRef: /links/image
  weight: 30
